openhab:
    image: "openhab/openhab:2.2.0-snapshot-amd64"
    restart: always
    net: host
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/etc/timezone:/etc/timezone:ro"
        - "./addons:/openhab/addons"
        - "./conf:/openhab/conf"
        - "./userdata:/openhab/userdata"
    environment:
        OPENHAB_HTTP_PORT: "8080"
        OPENHAB_HTTPS_PORT: "8443"
